application: downloadlabums
version: 1
runtime: python27
api_version: 1
threadsafe: False


handlers:
- url: /media/
  static_dir: media

- url: /.*
  script: djangoappengine/main/main.py

libraries:
- name: django
  version: "1.3"
